server:
  port: 9191
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lease?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: # 如果你的 docker 镜像没设置密码，这里留空
      database: 0
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数
          max-wait: -1ms

# 支付宝沙箱配置
alipay:
  app-id: 9021000162612530
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDGibrBjqwQwjLtigqvu7OBEsdub8IC2ZbImdUC+lcsHdD0/4hmZrzTlrYxxzewEtgof+zsvjy8c3NLtr7RMBevHZnWWrCBtESon3BtKW57AFIEp9EzLHrbMu6JDMa3reXxMz5AkW07UAHkeJm1BrI79Ug8SIt6kT+qonGiLeFwhDqTdUQ5QkSDuO/gUxHFXXJw4uiEEN1rrQsjsuvrhuU6NDCUMkH/2yYENTphZVfFd2gREu0OsEeKt3g3kYiH8TZs9ejcs62LoAIrBrc497Ns8sGaKG8bl5sTXSAxsCOK1lq7C1XLwAa2MZDDLp+JUUBRw0NW7haAJBRha2C+7pWTAgMBAAECggEBAJrZ2dwWF4aKsYYsYOFoGT3XE83DRSNL6xtTQJ0t/MfgCZbNp+mWwDiYGEsDAyBF0mrkPDr6tgyWT5sCUhp+1Do1cEOMQJcpr1OF5/58jjtJqK8Q5U5wpvJI61vhpyykafCS8z8RLo1QfelhVyGms2WojkrWmlNi7rF8Of0wo+FJIPvYXh2zvUvDE8eHUqLyQ9zi52hD4vTJQxAuu/jr6fImVCYjsv65DVM4s6nBQZZCWKwLvQ15wndApSCjEutmcY4XFiWUTX7IWHykeaC8hQfDePPGPDkDgQ//4QlEwIbEK2XPm6he22A8shBREaQ05zpkRxh4VrAGQapi+q5ulwECgYEA7MzGrlbMWKMOEcO1yEfSMcDoGMoCQynQkKzbDq763G2tPkcF2GSDtSvd+evUFs40TXqmAvChCzbklMxA3460da5KzFT9sg/usle5pEHPU0bWGgW5SRZd7Fch/vYvZuGQu502cdDzWHbzhe89fBRDND31rf4zaacmJG944tcAkaECgYEA1qLBm1z+DLvnv/MCuQCDqoubMW5lfS+rmVPgekF+5gL0fqY9iPI0LsZ7PIU/n4X/Iz/2J3jVmfS7crAWPxZl+cu04uRpJBMIHi3TJIc5LJ938NgCVHr62V4hw1Un8TrY6ZGbRMdSj8L1RXqjyCQb/i2WfE1A0clSTqhDW/F1grMCgYBqBOzXVWk8LhS4g2U5/F3xhKrlnlwQ8gG9JIcXNeR/GGO+RFIrpiUJ0lAZ+yoD4+Kq5cS6AD46JSOGM0TAUsYdAiHfBhZnyJZYJsqo7gYDBO4KzJE+VdNLY1+HJXXnnAoO1b5witrIuskhKBHhIblNBIigk/U00m9TVM1M0nIgwQKBgQDFZWArs8WODo6f8S3S2U8+XTC4sHA0RtBJrmNn7K55ecREaj1zolUto6sZSO7vlnvEfoGzYaUI95QhcSK0mLPmnVtZxHmSDNLNdpWWJasGiA71+KOD8KqdmL3yeHHIoLd3cEtdYPdkcgfDA3x3iAYaqPCaly4DAmVpI8T3XUUWkwKBgAV2n1RdmuEtNkfFxGVxhkVmOYIu+JBh+LHsnsVE/wSji2miZu9FF9jczRlK2z0xIqMJix2Cx12hm8xyaHCJvaCx+wv92RdCPG2+/VTDD9BMPA+P2oNqvnSbxTiKK+t4aBjqUxTCO/c/PVZVbPqxeLk8ql8A3lSz3hpbrNW3Wa2t
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAh+LZXWAuGsEC0H7tReFEbnyzZIboAwbIwosV76MQnpKSrTpRSH3s39L4f80CWmNbvEtQoV67nZVQTnYzqiTScyoQdP71Xb1Us9E+Y/l99zDvabpXQeMsdRJJhv/4ZH6qocDcXGiM+jAbvfHcsh4dSGX7x9BQoZHRfweAJUdRuGlZtkNLtV5fFDLzpW5nx59U/w9nM37sUyiihh9D5vYn8yYyddgCiFT6uqal98kq/6yPRPAPdpEdQCghMNooLDU1kzswHPC1uLjGIRNj2XhARJ1NDCIz/+eBm/pBqOtH2tiY3z72DWHdBD41RkhhPPKW0Rv8YomxZIQVD12tAcjPNQIDAQAB
  # ⚠️ 注意：现在的沙箱网关已经换成最新的下面这个了，别用网上的老教程
  server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  sign-type: RSA2
  charset: UTF-8
  format: JSON
  # 支付成功后，支付宝引导用户浏览器跳转回你的前端页面的地址
  return-url: http://localhost:5173/profile
  # 支付宝服务器在后台悄悄通知你后端支付成功的地址 (后续讲内网穿透时再填，先随便写一个)
  notify-url: http://g9256f44.natappfree.cc/api/order/notify


mybatis-plus:
  mapper-locations: classpath:com/luo/share/mapper/*.xml

jwt:
  secret: agri_share_platform_secret_key_must_be_long_enough_2026 # 密钥必须够长
  expiration: 21600 # 6小时的秒数 (6 * 60 * 60)
