server:
  port: 9191
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lease?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: # 如果你的 docker 镜像没设置密码，这里留空
      database: 0
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数
          max-wait: -1ms

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB    # 单个文件最大限制 (设为10MB，兜底前端的5MB)
      max-request-size: 50MB

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com  # 替换为你的真实 endpoint
    access-key-id:   # 替换为你的真实 ID
    access-key-secret:   # 替换为你的真实 Secret
    bucket-name:      # 替换为你的真实 Bucket 名称

# 支付宝沙箱配置
alipay:
  app-id:
  private-key:
  server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  sign-type: RSA2
  charset: UTF-8
  format: JSON
  # 支付成功后，支付宝引导用户浏览器跳转回你的前端页面的地址
  return-url: http://localhost:5173/profile
  # 支付宝服务器在后台悄悄通知你后端支付成功的地址 (后续讲内网穿透时再填，先随便写一个)
  notify-url: http://x469cdb9.natappfree.cc/api/order/notify
  alipay-public-key:




mybatis-plus:
  mapper-locations: classpath:com/luo/share/mapper/*.xml

jwt:
  secret:  # 密钥必须够长
  expiration: 21600 # 6小时的秒数 (6 * 60 * 60)
